### PR TITLE
Update to latest poly-decomp.js API

### LINKED ISSUE #287: poly-decomp API has changed
Looks like poly-decomp API changed slightly in the newest version

Trying to instantiate a Polygon body from concave vertices results in an error: `decomp.Polygon is not a constructor`

As a workaround it's possible to use the old version: https://github.com/schteppe/poly-decomp.js/commit/4558762effada60404c10c46d1d995c9512d87f5

### PR DESCRIPTION
**Pull request by RobertHerhold**
Resolves #287.

### CODE REVIEW

**Comment by BorisKozo** [comment]
@liabru @RobertHerhold   Any progress with this? Do you want me to look at the conflicts?
I am using it with webpack and it will be nice to have the latest versions loaded through npm.

**Comment by liabru** [comment]
Merged, thanks!

**Comment by ethanking2** [comment]
Even with these changes, I'm still getting this issue is there any way to fix it.

**Comment by cakar** [comment]
I have the same issue. I am trying to make a line into a body through Bodies.fromVertices btw. I am also open to ideas.

**Pull request merged**
