### PR TITLE
Use svg instead of png to get better image quality

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by derhuerst** [comment]
Why not merge this?

**Comment by PeterDaveHello** [comment]
yeah, why not? ha

**Comment by liabru** [comment]
There's nothing wrong with the png version of the badge, thanks anyway.

**Comment by derhuerst** [comment]
The SVG version has many advantages, the biggest one being accessibility: The SVG is accessible for both screen readers and web scrapers (like search engines, instapaper, etc).

A small bonus: The SVG is retina-friendly. (;

**Pull request closed without merging**
