### PR TITLE
use es6 Set in Pairs.update

### PR DESCRIPTION
**Pull request by payload**

### CODE REVIEW

**Comment by liabru** [comment]
This breaks compatibility with older browsers which I'd like to support, there must be a fallback.

So while I can't accept this particular commit, you raise a good point about using more modern features (where available). I've opened issue #508 for this which you can track for this, thanks.

**Comment by bchevalier** [comment]
I just implemented a solution that might be even more performant:
https://github.com/liabru/matter-js/pull/522

**Comment by getkey** [comment]
Since #522 has been merged, this PR can probably be closed.

**Comment by liabru** [comment]
Agreed, closing since a different solution is now implemented. But the spirit of this pull request still lives on in #508.

**Pull request closed without merging**
