### PR TITLE
Updated pixi.js to v3

### PR DESCRIPTION
**Pull request by upisfree**
I used *compound-concave* like *dev* branch, it's ok?

[1](https://github.com/liabru/matter-js/blob/419d2addcac1f96bdf6665595760cda7610034e7/src/render/RenderPixi.js#L75). ParticleContainer (former SpriteBatch) can render just one texture, that's why I use just Container.
[2](https://github.com/liabru/matter-js/blob/419d2addcac1f96bdf6665595760cda7610034e7/src/render/RenderPixi.js#L235). In Render.world we render just bodies, right? What if we have another thing in main container, like a gui or something?
[3](https://github.com/liabru/matter-js/blob/419d2addcac1f96bdf6665595760cda7610034e7/src/render/RenderPixi.js#L372). Pixi operates with sprites very fast but with graphics — slowly. Why not could we create sprite in canvas?

Sorry, my English is very bad, that's why my message looks... so aggressive, maybe?

Matter is the best JavaScript physics engine that I saw.

### CODE REVIEW

**Comment by liabru** [comment]
Cool, I'll try this out soon.

re. 2: the built in renderer is only a minimal example, for anything more you should create a [custom renderer](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-renderer)

re 3: do you mean cache vector graphics? I thought about it, but it's kind of out of the scope of the demo renderer, I prefer to keep it simple for now

**Comment by upisfree** [comment]
@liabru yes, cache. I'll make the demo of it on weekends.

**Comment by liabru** [comment]
I've tried this out, looks good but could you please make the following amends?

- fix bug when resizing browser: canvas only scales on x-axis (remove `autoResize: true`?)
- add pixi.js.map (see console error)
- change `render.bodies` to `render.spriteContainer` (only use `bodies` to refer to Matter.Body instances)
- remove both of your inline comments

Thanks

**Comment by upisfree** [comment]
@liabru done.

**Comment by liabru** [comment]
This has been merged into master. Thanks for the contribution!

**Pull request closed without merging**
